name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v5

    - name: phpunit
      uses: php-actions/phpunit@v3
      with:
        php_version: 8.0
